FROM registry.access.redhat.com/ubi8/ubi:latest
RUN yum -y update && \
    yum -y install python3 python3-pip

LABEL maintainer="info@opsmx.io"
LABEL version="1.0"
LABEL description="A small container that mimics HashiCorp Enterprise Vault \
policy integration with HashiCorp Sentinel"

COPY ./app /app
WORKDIR /app

RUN pip3 install -r requirements.txt

EXPOSE 8200

CMD ["python3", "vault-lite.py"]
