---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-lite
  namespace: spinnaker
  labels:
    app: vault-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-lite
  template:
    metadata:
      labels:
        app: vault-lite
    spec:
      containers:
      - name: vault-lite
        image: zappo/vault-lite:latest
        ports:
        - containerPort: 8200
        env:
          - name: VAULT_LITE_PORT
            value: "8200"
          - name: PREFIX_PATH
            value: "/vault-lite"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-lite
  namespace: spinnaker
spec:
  type: ExternalName
  externalName: vault-lite.spinnaker.svc.cluster.local
  selector:
    app: vault-lite
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
